version: '3.9'
services:
  db:
    image: postgres:15
    container_name: ai_ethics_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_ethics_sim
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai_ethics_backend
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/ai_ethics_sim
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data: